language: python
sudo: false
python:
  - "3.6"
cache: pip

before_script:
  - pip3.6 install coverage
  - python3.6 -m coverage run --source=retro setup.py test

script:
  - python3.6 -m coverage report
