FROM tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7

RUN apk update && apk add build-base

COPY ./retro /app/retro
COPY ./uwsgi.ini /app
COPY ./conf /app/conf

COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt
