FROM python:3.6-alpine

RUN apk update && apk add build-base

RUN mkdir /app

COPY ./retro /app/retro

COPY setup.py /app/setup.py
RUN pip install --upgrade pip
RUN python3.6 /app/setup.py install

ENV PYTHONPATH="$PYTHONPATH:/app"

CMD ["python3.6", "/app/retro/websocket_server/app.py"]
