FROM python:3.6-alpine

RUN apk update && apk add build-base

RUN mkdir /app

COPY ./retro /app/retro

COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

ENV PYTHONPATH="$PYTHONPATH:/app"

CMD ["python3.6", "/app/retro/websocket_server/app.py"]
