FROM tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7

RUN apk update && apk add build-base

COPY ./retro /app/retro
COPY ./uwsgi.ini /app
COPY ./conf /app/conf

COPY setup.py /app/setup.py
RUN pip install --upgrade pip
RUN python3.6 /app/setup.py install
